[package]
name = "ipm-common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra-sparse = "0.10.0"
log = "0.4.26"
