[package]
name = "clipm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ocl = "0.19"
nalgebra-sparse = "0.9.0"
log = "0.4.19"
